name: spotify-archetypes-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.2.*
  - numpy=2.1.*
  - scikit-learn=1.6.1=py311h*
  - joblib=1.4.*
  - fastapi=0.135.*
  - uvicorn=0.42.*
  - jupyter
  - ipykernel
  - pytest
  - pytest-cov
  - pip
  - pip:
      - conda-lock
      - python-dotenv
      - wandb